CREATE SEQUENCE CONTATOS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE LIXO_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE COLETA_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_CONTATOS (
    ID INTEGER DEFAULT CONTATOS_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
    RUA VARCHAR(100),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    CEP VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE TBL_LIXO (
    ID INTEGER DEFAULT LIXO_SEQ.NEXTVAL NOT NULL,
    CAPACIDADE NUMBER,
    LOCALIZACAO VARCHAR(80),
    TIPO VARCHAR(50),
    DESCRICAO VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE TBL_COLETA_AGENDADA (
    ID INTEGER DEFAULT COLETA_SEQ.NEXTVAL NOT NULL,
    CONTATO_ID INTEGER NOT NULL,
    LIXO_ID INTEGER NOT NULL,
    DATA_COLETA DATE,
    STATUS VARCHAR(50),
    OBSERVACOES VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (CONTATO_ID) REFERENCES TBL_CONTATOS(ID),
    FOREIGN KEY (LIXO_ID) REFERENCES TBL_LIXO(ID)
);
